[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
rootDirectory = "VeriVault/verivault-v2/server"

[env]
NODE_ENV = "production"
PORT = "8080" 