[build]
builder = "nixpacks"
buildCommand = "npm run build"
watchPatterns = ["src/**"]

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "npm start"

[env]
NODE_ENV = "production"
PORT = "8080" 